const articoli = [
  {
    slug: "agenzie-abusive-verona",
    titolo: "7 agenzie abusive e 15 agenti senza patentino scoperti a Verona. Non è un caso isolato.",
    excerpt: "La Guardia di Finanza di Legnago ha scoperto nel Veronese sette agenzie e 15 agenti immobiliari che operavano senza le abilitazioni richieste dalla legge. Ecco perché accade — e come proteggersi.",
    categoria: "Trasparenza",
    tagClass: "red",
    data: "24 Aprile 2026",
    lettura: "5 min",
    featured: true,
    cta: { testo: "Vedi una scheda immobile →", link: "/compra/1" },
    sezioni: [
      { tipo: "paragrafo", testo: "Il 24 aprile 2026 la Guardia di Finanza di Legnago ha reso noti i risultati di un'operazione nel Veronese: **7 agenzie immobiliari e 15 mediatori** operavano senza la prescritta iscrizione nel Registro delle Imprese e senza alcun titolo abilitativo. Sanzioni da 7.500 a 15.000 euro per ciascuno, e segnalazioni alla Camera di Commercio per le agenzie che li avevano assunti." },
      { tipo: "paragrafo", testo: "Leggendo la notizia, la prima reazione è spesso sorpresa. La seconda, se hai comprato o venduto casa negli ultimi anni, potrebbe essere qualcosa di più scomodo." },
      { tipo: "titolo", testo: "Cosa ha scoperto la GdF" },
      { tipo: "paragrafo", testo: "L'indagine è partita da un controllo su un singolo mediatore che operava per un'agenzia della bassa veronese. Da lì, gli accertamenti si sono allargati: nell'arco di due anni i finanzieri hanno individuato 7 agenzie nei Comuni di Legnago e Cerea. Nessuno dei 15 agenti risultava iscritto nella sezione dedicata del Registro delle Imprese." },
      {
        tipo: "dati",
        titolo: "I numeri dell'operazione",
        colore: "red",
        righe: [
          ["Agenzie abusive scoperte", "7"],
          ["Agenti senza patentino", "15"],
          ["Sanzione per ciascuno", "€7.500 – €15.000"],
          ["Comuni coinvolti", "Legnago e Cerea (VR)"],
          ["Durata dell'indagine", "2 anni"],
        ],
        fonte: "ANSA, 24 aprile 2026 · Guardia di Finanza di Legnago",
      },
      { tipo: "paragrafo", testo: "Nel frattempo questi agenti **gestivano direttamente le trattative di compravendita**: accompagnavano i clienti nelle visite, raccoglievano proposte di acquisto, assistevano nella predisposizione dei contratti preliminari. Tutto ciò che fa un agente regolare — senza averne i requisiti." },
      { tipo: "titolo", testo: "Perché questo accade — e perché è un problema strutturale" },
      { tipo: "paragrafo", testo: "La legge italiana (n. 39/1989) stabilisce che per esercitare l'attività di mediazione immobiliare è necessario superare un esame abilitativo e iscriversi al Registro delle Imprese. Un percorso che richiede tempo, studio e costi. Il risultato? Un incentivo a operare nell'ombra, soprattutto in mercati locali dove i controlli sono rari." },
      { tipo: "citazione", testo: "Il problema non sono 15 agenti a Verona. Il problema è un modello di intermediazione che rende difficile distinguere chi è abilitato da chi non lo è — e che scarica tutto il rischio sul cliente." },
      { tipo: "titolo", testo: "Le commissioni che hai pagato erano legittime?" },
      { tipo: "paragrafo", testo: "Se hai comprato o venduto casa tramite un'agenzia, hai il diritto di verificare che il tuo interlocutore fosse regolarmente abilitato. Puoi farlo sul portale del **Registro delle Imprese** (registroimprese.it) cercando la ragione sociale nella sezione dedicata alla mediazione immobiliare." },
      { tipo: "titolo", testo: "Il mercato immobiliare italiano: grandi numeri, poca trasparenza" },
      { tipo: "paragrafo", testo: "Nel 2025 in Italia sono state registrate **766.756 compravendite residenziali** (+6,5% sul 2024). Il fatturato dell'intermediazione immobiliare vale circa 14,3 miliardi di euro all'anno. È un mercato enorme, frammentato in oltre 38.000 micro-agenzie. In questo contesto, la verifica degli abilitati è affidata quasi interamente agli acquirenti stessi." },
      { tipo: "titolo", testo: "Cosa cambia con RealAIstate" },
      { tipo: "paragrafo", testo: "RealAIstate nasce esattamente da questo problema. Non dal desiderio di eliminare i professionisti del settore — ma dall'esigenza di costruire un modello in cui **trasparenza e verifica siano strutturali**, non opzionali. Il Fair Price Score è basato su dati pubblici. Le commissioni sono fisse e dichiarate prima di iniziare." },
    ],
    fonte: "ANSA, 24 aprile 2026 · Guardia di Finanza di Legnago · Agenzia delle Entrate / OMI, Statistiche IV trimestre 2025",
  },

  {
    slug: "mercato-immobiliare-2025-dati",
    titolo: "766.756 compravendite nel 2025: il mercato immobiliare italiano è in piena accelerazione.",
    excerpt: "I dati OMI del IV trimestre 2025 confermano: il mercato immobiliare italiano cresce del 6,5% anno su anno. Cosa significa per chi vuole comprare o vendere casa oggi.",
    categoria: "Mercato",
    tagClass: "gold",
    data: "20 Aprile 2026",
    lettura: "6 min",
    featured: false,
    cta: { testo: "Scopri la metodologia →", link: "/metodologia" },
    sezioni: [
      { tipo: "paragrafo", testo: "L'Agenzia delle Entrate ha pubblicato le statistiche OMI del IV trimestre 2025. Il dato più significativo: nel corso dell'intero anno 2025 sono state registrate in Italia **766.756 compravendite residenziali**, con una crescita del 6,5% rispetto alle 719.578 del 2024." },
      {
        tipo: "dati",
        titolo: "Il mercato immobiliare in cifre — 2025",
        colore: "gold",
        righe: [
          ["Compravendite residenziali 2025", "766.756"],
          ["Variazione YoY", "+6,5%"],
          ["Compravendite residenziali 2024", "719.578"],
          ["Tasso mutuo medio (IV trim. 2025)", "3,5%"],
          ["Acquisti con mutuo ipotecario", "< 45%"],
          ["Acquisti prima casa", "~72%"],
          ["Nuovi contratti di locazione (IV trim.)", "~278.000"],
        ],
        fonte: "Agenzia delle Entrate — OMI, Statistiche trimestrali IV 2025",
      },
      { tipo: "titolo", testo: "Cosa dicono i dati trimestre per trimestre" },
      { tipo: "paragrafo", testo: "La crescita del 2025 non è stata uniforme. Il IV trimestre, con oltre **218.000 compravendite**, ha mostrato una crescita più contenuta (+0,4% tendenziale). Il rallentamento è concentrato nei comuni capoluogo del Sud, mentre i comuni non capoluogo del Nord Ovest hanno continuato a crescere." },
      { tipo: "titolo", testo: "I mutui: il tasso sale, la quota scende" },
      { tipo: "paragrafo", testo: "La quota di acquisti finanziati con mutuo ipotecario è scesa sotto il 45%. Il tasso medio applicato alla prima rata ha raggiunto il **3,5%**. Sempre più acquirenti stanno comprando senza ricorrere al mutuo — probabilmente perché hanno liquidità propria, o perché i tassi rendono il finanziamento meno conveniente." },
      { tipo: "citazione", testo: "766.756 transazioni in un anno. Ognuna con una commissione. Il mercato cresce — ma il costo dell'intermediazione rimane invariato, percentuale sul prezzo." },
      { tipo: "titolo", testo: "Cosa significa per chi compra o vende casa" },
      { tipo: "paragrafo", testo: "Un mercato in crescita è generalmente una buona notizia per i venditori — più domanda significa più acquirenti potenziali e tempi di vendita più brevi. Per i compratori, invece, un mercato attivo significa più concorrenza sugli immobili migliori e meno margine di negoziazione." },
      { tipo: "paragrafo", testo: "C'è però un elemento che rimane costante: **il costo dell'intermediazione immobiliare**. Su un appartamento da €300.000 a Milano, una commissione del 3% significa €9.000. Al 6% (compratore + venditore) si arriva a €18.000." },
      { tipo: "titolo", testo: "Il Fair Price Score: sapere se il prezzo è giusto, prima di firmare" },
      { tipo: "paragrafo", testo: "RealAIstate calcola il **Fair Price Score** di ogni immobile usando i dati OMI ufficiali dell'Agenzia delle Entrate — gli stessi dati usati in questo articolo. Non una stima soggettiva: un calcolo trasparente, verificabile da chiunque, aggiornato ogni semestre." },
    ],
    fonte: "Agenzia delle Entrate — Osservatorio del Mercato Immobiliare (OMI), Statistiche trimestrali residenziale IV 2025",
  },

  {
    slug: "commissioni-agenzia-quanto-costano",
    titolo: "Quanto costa davvero un'agenzia immobiliare? Il conto che nessuno ti fa.",
    excerpt: "3-6% di commissione sul prezzo di vendita. Su una casa da €300.000 significa fino a €18.000 che escono dalla tua tasca. Ecco tutto quello che devi sapere prima di firmare un mandato.",
    categoria: "Trasparenza",
    tagClass: "red",
    data: "15 Aprile 2026",
    lettura: "5 min",
    featured: false,
    cta: { testo: "Compra o vendi senza agenzia →", link: "/compra" },
    sezioni: [
      { tipo: "paragrafo", testo: "Quando firmi un mandato con un'agenzia immobiliare, stai accettando di pagare una percentuale sul prezzo finale della tua casa. Sembra semplice. Ma il conto reale — quello che nessuno ti fa vedere prima di firmare — è molto più alto di quello che ti aspetti." },
      { tipo: "titolo", testo: "Come funziona il sistema delle commissioni" },
      { tipo: "paragrafo", testo: "In Italia la commissione media di un'agenzia immobiliare è tra il **3% e il 6%** del prezzo di vendita — e si applica sia al venditore che al compratore. Su una casa da €300.000, questo significa fino a **€9.000 a testa**, per un totale di **€18.000** che escono dalla transazione." },
      {
        tipo: "dati",
        titolo: "Il conto reale delle commissioni",
        colore: "red",
        righe: [
          ["Casa da €200.000 — commissione 3%+3%", "€12.000 totali"],
          ["Casa da €300.000 — commissione 3%+3%", "€18.000 totali"],
          ["Casa da €500.000 — commissione 3%+3%", "€30.000 totali"],
          ["Casa da €800.000 — commissione 2%+2%", "€32.000 totali"],
          ["RealAIstate — fee fissa compratore", "€3.000"],
        ],
        fonte: "Elaborazione RealAIstate su pratiche di mercato comuni",
      },
      { tipo: "titolo", testo: "Il mandato: cosa stai firmando davvero" },
      { tipo: "paragrafo", testo: "Il mandato di vendita è il contratto che firmi con l'agenzia. Può essere **aperto** (puoi vendere anche da solo o con altre agenzie) o **in esclusiva** (solo quell'agenzia può vendere per un periodo determinato, tipicamente 3-6 mesi). L'esclusiva suona come un vantaggio — l'agenzia si impegna di più — ma in realtà ti toglie potere negoziale. Se non vendi entro i termini, sei comunque vincolato." },
      { tipo: "citazione", testo: "L'agenzia guadagna quando chiude la trattativa — non quando chiude al prezzo migliore per te. Questo conflitto di interessi è strutturale, non un'eccezione." },
      { tipo: "titolo", testo: "Cosa paghi davvero con quella commissione" },
      { tipo: "paragrafo", testo: "La risposta onesta: le visite, le fotografie, la pubblicazione dell'annuncio sui portali e la mediazione tra le parti. Sono servizi reali. Ma il loro costo effettivo — ore di lavoro, strumenti, pubblicità — è molto lontano da €9.000 o €18.000. La commissione percentuale non riflette il costo del servizio: riflette il valore dell'immobile. E il tuo valore non ha nulla a che fare con il lavoro dell'agente." },
      { tipo: "titolo", testo: "I costi che non vedi" },
      { tipo: "paragrafo", testo: "Oltre alla commissione, una compravendita porta con sé altri costi spesso sottovalutati: **imposta di registro** (2% prima casa, 9% seconda casa sul valore catastale), **spese notarili** (€1.500–€3.000), **perizia APE** (€150–€300), **spese condominiali arretrate** se presenti. Prima di comprare o vendere, il quadro economico completo è fondamentale." },
      { tipo: "titolo", testo: "Un modello alternativo esiste" },
      { tipo: "paragrafo", testo: "RealAIstate ha scelto un modello diverso: **fee fissa di €3.000 per il compratore**. Non una percentuale. Non un incentivo a far salire il prezzo o a chiudere in fretta. Un costo dichiarato, fisso, uguale per tutti. La valutazione dell'immobile è basata su dati pubblici OMI — non su stime soggettive dell'agente. La trasparenza non è uno slogan: è la struttura del servizio." },
    ],
    fonte: "Elaborazione RealAIstate · Agenzia delle Entrate / OMI 2025 · FIAIP 2024",
  },

  {
    slug: "under-36-agevolazioni-prima-casa",
    titolo: "Under 36 e prima casa: le agevolazioni fiscali che nessuno ti spiega fino in fondo.",
    excerpt: "Imposta di registro al 2%, esenzione IMU, garanzia Consap fino all'80% del mutuo. Se hai meno di 36 anni e stai comprando la prima casa, potresti risparmiare migliaia di euro — ma solo se sai come funziona davvero.",
    categoria: "Normativa",
    tagClass: "gray",
    data: "10 Aprile 2026",
    lettura: "7 min",
    featured: false,
    cta: { testo: "Verifica la tua capacità d'acquisto →", link: "/compra/1" },
    sezioni: [
      { tipo: "paragrafo", testo: "In Italia comprare la prima casa è già complicato. Farlo sotto i 36 anni, con un mutuo, in un mercato che cresce del 6,5% anno su anno, sembra quasi impossibile. Eppure esistono strumenti che possono fare una differenza concreta — fiscale, finanziaria, reale. Il problema è che quasi nessuno te li spiega davvero fino in fondo." },
      { tipo: "titolo", testo: "Chi può accedere alle agevolazioni under 36" },
      { tipo: "paragrafo", testo: "Le agevolazioni fiscali prima casa per i giovani sono riservate a chi, **alla data del rogito**, non ha ancora compiuto 36 anni e ha un **ISEE non superiore a €40.000**. L'immobile deve essere destinato ad abitazione principale: non può essere una casa di lusso (categorie catastali A/1, A/8, A/9), non può essere già posseduta un'altra abitazione per la quale si sono già usate le agevolazioni prima casa." },
      {
        tipo: "dati",
        titolo: "Agevolazioni under 36 prima casa — riepilogo",
        colore: "gray",
        righe: [
          ["Età massima al rogito", "35 anni e 364 giorni"],
          ["ISEE massimo", "€40.000"],
          ["Imposta di registro", "2% (vs 9% ordinario)"],
          ["Imposta ipotecaria e catastale", "€50 ciascuna (vs % ordinaria)"],
          ["Credito d'imposta su IVA (nuovo)", "Pari all'IVA pagata"],
          ["Garanzia Consap sul mutuo", "Fino all'80% del valore"],
          ["Esenzione imposta sostitutiva mutuo", "Sì"],
        ],
        fonte: "Agenzia delle Entrate · Legge di Bilancio 2024",
      },
      { tipo: "titolo", testo: "Quanto si risparmia davvero" },
      { tipo: "paragrafo", testo: "Su una casa da **€250.000**, l'imposta di registro ordinaria sarebbe del 9% sul valore catastale — diciamo €4.500. Con le agevolazioni under 36 scende al 2%, quindi circa **€1.000**. Un risparmio di €3.500 solo sull'imposta di registro. A questo si aggiunge l'esenzione dall'imposta sostitutiva sul mutuo (normalmente 0,25% dell'importo finanziato: su €180.000 di mutuo, altri €450 risparmiati)." },
      { tipo: "citazione", testo: "Non è un bonus. È un diritto. Ma bisogna sapere come richiederlo, quando e a chi — perché nessuno lo fa automaticamente al posto tuo." },
      { tipo: "titolo", testo: "La garanzia Consap: il mutuo che sembrava impossibile" },
      { tipo: "paragrafo", testo: "Il Fondo di Garanzia Prima Casa (gestito da Consap) permette allo Stato di garantire fino all'**80% della quota capitale** del mutuo. In pratica: se non hai abbastanza liquidità per l'anticipo — che le banche normalmente chiedono al 20% — lo Stato fa da garante al posto tuo. Non è un prestito: è una garanzia pubblica che riduce il rischio per la banca e ti permette di accedere al mutuo anche con un anticipo minore." },
      { tipo: "paragrafo", testo: "Per i giovani under 36 con ISEE entro €40.000, la garanzia Consap è cumulabile con le altre agevolazioni fiscali. Il tasso applicato rimane quello di mercato, ma l'accesso al mutuo diventa possibile anche per chi non ha ancora accumulato un capitale significativo." },
      { tipo: "titolo", testo: "La trappola dell'ISEE: quando l'agevolazione scompare" },
      { tipo: "paragrafo", testo: "L'ISEE è il tallone d'Achille di queste agevolazioni. La soglia di €40.000 sembra alta, ma l'ISEE non è solo il reddito: include anche il **patrimonio mobiliare e immobiliare** (conti correnti, investimenti, case di proprietà dei genitori se sei nel nucleo familiare). Molti giovani scoprono di essere fuori soglia non per il reddito, ma per i risparmi o per le proprietà dei genitori incluse nell'ISEE familiare. Vale la pena verificarlo prima di iniziare a cercare casa." },
      { tipo: "titolo", testo: "Cosa cambia se compri senza agenzia" },
      { tipo: "paragrafo", testo: "Le agevolazioni fiscali si applicano indipendentemente da come compri — tramite agenzia o direttamente. Ma c'è una differenza concreta: **la commissione dell'agenzia non è agevolata**. Se paghi €9.000 di commissione a un'agenzia, quei €9.000 escono dalla tua tasca senza detrazioni. Con RealAIstate la fee fissa è €3.000 — e il risparmio di €6.000 si somma a quello fiscale. Per un under 36 con un mutuo importante, la differenza totale può superare i €10.000." },
    ],
    fonte: "Agenzia delle Entrate · Consap · Legge di Bilancio 2024 · Circolare MEF 2023",
  },

  {
    slug: "fair-price-score-come-funziona",
    titolo: "Il Fair Price Score: perché la valutazione di un immobile non dovrebbe dipendere dall'umore di un agente.",
    excerpt: "Per decenni il prezzo di una casa è stato stabilito da chi aveva interesse a venderla il più velocemente possibile. Il Fair Price Score cambia tutto — con dati pubblici, metodologia trasparente e zero conflitti di interesse.",
    categoria: "Guide",
    tagClass: "gray",
    data: "5 Aprile 2026",
    lettura: "5 min",
    featured: false,
    cta: { testo: "Scopri la metodologia completa →", link: "/metodologia" },
    sezioni: [
      { tipo: "paragrafo", testo: "Quanto vale davvero la casa che stai comprando? O quella che stai vendendo? Per decenni la risposta è dipesa da un agente immobiliare che, dopo una visita veloce e qualche confronto con le compravendite recenti della zona, ti diceva un numero. Quel numero era spesso una stima onesta. Ma era anche, inevitabilmente, influenzato da chi lo dava — e da cosa aveva interesse a ottenere." },
      { tipo: "titolo", testo: "Il problema con le valutazioni tradizionali" },
      { tipo: "paragrafo", testo: "L'agente che valuta il tuo immobile per venderlo ha un incentivo a dirti un prezzo alto — così accetti il mandato. Ma poi ha un incentivo a farti scendere velocemente — così chiude la trattativa e incassa la commissione. Questi due incentivi sono in contraddizione tra loro, e tu sei nel mezzo. Il risultato è che la valutazione tradizionale non è una stima oggettiva: è una negoziazione mascherata da consulenza." },
      { tipo: "citazione", testo: "Una valutazione che dipende da chi la fa non è una valutazione. È un'opinione. E le opinioni si pagano, anche quando sono sbagliate." },
      { tipo: "titolo", testo: "Cosa sono i dati OMI e perché sono diversi" },
      { tipo: "paragrafo", testo: "L'**Osservatorio del Mercato Immobiliare** (OMI) è una struttura dell'Agenzia delle Entrate che raccoglie e pubblica, ogni semestre, i valori medi di mercato per ogni tipologia di immobile in ogni zona del territorio italiano. Questi dati derivano dalle compravendite effettivamente registrate — non da annunci, non da stime, non da opinioni. Sono i numeri che usa il fisco per calcolare le imposte. Sono pubblici, gratuiti, aggiornati due volte l'anno." },
      { tipo: "paragrafo", testo: "Per ogni zona omogenea, l'OMI pubblica un **range di valori al metro quadro** distinto per tipologia (abitazioni civili, di lusso, economiche), stato conservativo (ottimo, normale, scadente) e destinazione (residenziale, commerciale, produttiva). La combinazione di questi parametri permette di posizionare ogni immobile all'interno di una fascia di prezzo oggettiva e verificabile." },
      { tipo: "titolo", testo: "Come funziona il Fair Price Score" },
      { tipo: "paragrafo", testo: "Il Fair Price Score di RealAIstate trasforma i dati OMI in un numero da 0 a 100 che risponde a una domanda semplice: **il prezzo richiesto è in linea con il mercato reale?** Il calcolo parte dalla superficie catastale dell'immobile, scorporando il valore di eventuali pertinenze (garage, cantine) che hanno range OMI distinti. Il prezzo al metro quadro dell'abitazione viene poi posizionato all'interno del range OMI della zona, pesando lo stato conservativo e la tipologia." },
      {
        tipo: "dati",
        titolo: "Esempio di calcolo — abitazione zona centrale Milano",
        colore: "gray",
        righe: [
          ["Prezzo totale richiesto", "€350.000"],
          ["Superficie abitazione", "75 mq"],
          ["Garage incluso (15 mq × €2.200/mq OMI)", "– €33.000"],
          ["Prezzo abitazione pura", "€317.000"],
          ["Prezzo/mq corretto", "€4.227/mq"],
          ["Range OMI zona — Abitazioni Civili Normale", "€3.500 – €5.500/mq"],
          ["Posizione nel range", "36,3% — primo terzo"],
          ["Fair Price Score", "85/100"],
        ],
        fonte: "Agenzia delle Entrate / OMI · Metodologia RealAIstate",
      },
      { tipo: "titolo", testo: "Perché questo è innovativo" },
      { tipo: "paragrafo", testo: "Prima di RealAIstate, i dati OMI erano accessibili ma inutilizzabili per chi non era un professionista del settore. Richiedevano di conoscere la zona omogenea dell'immobile, di interpretare le fasce di valori, di fare i calcoli a mano. Il Fair Price Score automatizza questo processo e lo rende comprensibile a chiunque — compratore o venditore — in pochi secondi." },
      { tipo: "paragrafo", testo: "La vera innovazione non è tecnica: è di sistema. Per la prima volta, chi compra casa ha accesso alla **stessa informazione** che ha chi la vende. Non un'opinione più o meno qualificata: un dato oggettivo, verificabile, aggiornato. La trasparenza non come valore astratto, ma come strumento concreto di tutela." },
      { tipo: "titolo", testo: "I limiti che non nascondiamo" },
      { tipo: "paragrafo", testo: "Il Fair Price Score è uno strumento potente, ma non è infallibile. I dati OMI sono aggiornati semestralmente — in mercati in rapido movimento, possono non catturare picchi o cali recenti. Non tengono conto di caratteristiche molto specifiche (vista, luminosità, piano esatto, qualità dei finiture). Per questo il Fair Price Score è sempre accompagnato da un'analisi qualitativa dell'immobile e dalla raccomandazione di consultare un perito certificato per valutazioni legali o fiscali." },
    ],
    fonte: "Agenzia delle Entrate — Osservatorio del Mercato Immobiliare (OMI) · Metodologia RealAIstate",
  },

  {
    slug: "ai-real-estate-morgan-stanley",
    titolo: "L'AI cambierà il modo in cui compri casa. Secondo Morgan Stanley, vale $34 miliardi. In Italia, è già iniziato.",
    excerpt: "Un'analisi di Morgan Stanley stima $34 miliardi di efficienza che l'AI porterà al settore immobiliare entro il 2030. Ma cosa significa concretamente per chi compra o vende casa oggi?",
    categoria: "Mercato",
    tagClass: "gold",
    data: "28 Aprile 2026",
    lettura: "6 min",
    featured: false,
    cta: { testo: "Scopri come funziona RealAIstate →", link: "/come-funziona" },
    sezioni: [
      { tipo: "paragrafo", testo: "A luglio 2025, Morgan Stanley ha pubblicato un'analisi su come l'intelligenza artificiale sta trasformando il settore immobiliare globale. Il titolo era diretto: **$34 miliardi di efficienza entro il 2030**. Un numero enorme — ma anche astratto. Cosa significa, concretamente, per chi deve comprare o vendere casa oggi?" },
      { tipo: "titolo", testo: "Cosa ha trovato Morgan Stanley" },
      { tipo: "paragrafo", testo: "I ricercatori di Morgan Stanley hanno analizzato 162 aziende immobiliari americane — REIT e operatori commerciali — con 525.000 dipendenti e 92 miliardi di dollari di costi del lavoro. La conclusione: il **37% dei compiti svolti da questi lavoratori può essere automatizzato** dall'AI. Le aree con più potenziale? Gestione, vendite, supporto amministrativo, manutenzione." },
      {
        tipo: "dati",
        titolo: "AI nel real estate — i numeri di Morgan Stanley",
        colore: "gold",
        righe: [
          ["Efficienza stimata entro il 2030", "$34 miliardi"],
          ["Aziende analizzate", "162 REIT e CRE firms"],
          ["Dipendenti nel campione", "525.000"],
          ["Costi del lavoro totali", "$92 miliardi"],
          ["Quota di compiti automatizzabili", "37%"],
          ["Miglioramento cash flow (broker)", "+34%"],
        ],
        fonte: "Morgan Stanley Research, luglio 2025",
      },
      { tipo: "titolo", testo: "Dal commerciale al residenziale: cosa cambia per te" },
      { tipo: "paragrafo", testo: "L'analisi di Morgan Stanley è focalizzata sul mercato americano e sul segmento commerciale. Ma le dinamiche che descrive si applicano anche al residenziale — e all'Italia. L'AI può fare cose che prima richiedevano ore di lavoro di un agente: **valutare automaticamente un immobile** usando dati di mercato pubblici, **rispondere alle domande dei potenziali acquirenti** 24 ore su 24, **verificare la documentazione** e identificare incongruenze, **coordinare i professionisti** (notaio, perito, geometra) senza telefonate e attese." },
      { tipo: "citazione", testo: "Le aziende che usano l'AI per ridurre il personale in loco riportano una soddisfazione più alta da parte dei clienti — non più bassa. Perché l'AI non stanca, non ha fretta, non ha conflitti di interesse." },
      { tipo: "titolo", testo: "Il conflitto di interessi che l'AI elimina" },
      { tipo: "paragrafo", testo: "C'è una cosa che Morgan Stanley non dice esplicitamente, ma che i numeri implicano: **l'AI non ha incentivi distorti**. Un agente immobiliare guadagna quando chiude una trattativa — non quando la chiude al prezzo migliore per te. Questo crea un conflitto strutturale che è antico quanto il settore. L'AI applicata alla valutazione immobiliare usa dati pubblici, metodologie trasparenti e non ha commissioni da incassare. Il suo output non dipende da chi paga di più." },
      { tipo: "titolo", testo: "In Italia, stiamo già iniziando" },
      { tipo: "paragrafo", testo: "Il mercato immobiliare italiano è tra i più frammentati d'Europa: oltre 38.000 micro-agenzie, commissioni tra le più alte del continente, nessun sistema pubblico di verifica dei prezzi accessibile ai non professionisti. È esattamente il tipo di mercato dove l'AI può fare la differenza più grande — perché il punto di partenza è più lontano dall'efficienza." },
      { tipo: "paragrafo", testo: "RealAIstate applica al mercato residenziale italiano quello che Morgan Stanley descrive come il futuro del settore: valutazione automatica basata su dati OMI ufficiali, chat AI che media la comunicazione tra compratore e venditore, verifica della capacità d'acquisto in tempo reale, coordinamento dei professionisti in piattaforma. Non è fantascienza — è live su realaistate.ai, oggi." },
      { tipo: "titolo", testo: "Il risparmio che i $34 miliardi non dicono" },
      { tipo: "paragrafo", testo: "I $34 miliardi di Morgan Stanley misurano l'efficienza per le aziende immobiliari. Ma c'è un altro risparmio — quello per i clienti. Se l'AI riduce i costi operativi dell'intermediazione, quei risparmi possono essere trasferiti a chi compra e vende casa. Con RealAIstate la fee fissa è €3.000 invece del 3-6% tradizionale. Su una casa da €300.000, la differenza è fino a **€15.000**. Questo è il risparmio reale dell'AI nel real estate — non nei bilanci delle aziende, ma nelle tasche delle persone." },
    ],
    fonte: "Morgan Stanley Research, luglio 2025 · Agenzia delle Entrate / OMI 2025",
  },
];

export default articoli;
